In [37]:
__author__ = "Miguel Solinas ","Elvin Ugonna"
__credits__ = "Miguel Solinas Jr.","Elvin Ugonna"
__version__ = "0.1.0"
__maintainer__ = "Miguel Solinas Jr.","Elvin Ugonna"
__email__ = "migue.solinas@gmail.com","elvindavin@gmail.com"
__status__ = "Project"

In [32]:
#importing libraries
import pandas as pd
import numpy as np

In [7]:
#open dataset
file = pd.read_csv("data1.csv")
dataset = pd.DataFrame(file)
dataset.describe()

type          time       sender      messageID        pos/0  \
count  4029.0   4029.000000  4029.000000    4029.000000  4029.000000   
mean      4.0  18050.008896   236.864483  134793.972946  4719.204751   
std       0.0     28.807848   151.330926   75782.566687  1089.826240   
min       4.0  18000.006320     7.000000     153.000000  2331.525684   
25%       4.0  18024.733440   103.000000   70699.000000  3613.652104   
50%       4.0  18049.699190   217.000000  138293.000000  4426.073097   
75%       4.0  18074.727730   361.000000  201806.000000  5936.455077   
max       4.0  18099.997670   601.000000  260739.000000  6324.850321   

             pos/1         pos/2         spd/0        spd/1       classs  
count  4029.000000  4.029000e+03  4.029000e+03  4029.000000  4029.000000  
mean   5571.488144  1.895000e+00  1.797976e+00    -1.060090     1.846612  
std     258.697882  1.934249e-13  8.136849e+00    18.057582     0.360406  
min    5180.351961  1.895000e+00 -1.712646e+01   -43.874673     1.000000  
25%    5313.817688  1.895000e+00 -1.791909e+00    -6.191417     2.000000  
50%    5562.989770  1.895000e+00  8.530000e-15     0.000000     2.000000  
75%    5778.752997  1.895000e+00  5.579280e+00     2.175522     2.000000  
max    6080.031981  1.895000e+00  3.682722e+01    41.408049     2.000000

In [30]:
#  Descrpition:
#  Set of normalization functions
#  Normalize each columns of the dataset, this function accept a normalize function like argument (lambda : function()).
#  Args:
#   dataframe: pandas DataFrame of features
#   Normalize function: function to be implemented to normalize the dataset
#  Returns:
#    A version of the input `DataFrame` that has all its features normalized following the specified function.

def linear_scale(series):
  min_val = series.min()
  max_val = series.max()
  scale = (max_val - min_val) / 2.0
  return series.apply(lambda x:((x - min_val) / scale) - 1.0)

def z_score_normalize(series):
  mean = series.mean()
  std_dv = series.std()
  return series.apply(lambda x:(x - mean) / std_dv)

def get_quantile_based_boundaries(feature_values, num_buckets):
  boundaries = np.arange(1.0, num_buckets) / num_buckets
  quantiles = feature_values.quantile(boundaries)
  return [quantiles[q] for q in quantiles.keys()]

def feature_normalize(dataset):
    mu = np.mean(dataset,axis=0)
    sigma = np.std(dataset,axis=0)
    return (dataset - mu)/sigma

def min_max(dataset):
    mu = np.mean(dataset,axis=0)
    max_ = max(dataset)
    min_ = min(dataset)
    return (dataset - mu)/(max_-min_)



In [40]:
# We need to split the dataset into three (validation, training and testing)
# They must to be the same everytime, we can respect that by choosing a random seed (in this case 1)

def split_dataset (dataframe,validation=False,seed=1):
    np.random.seed(seed) 
    mask1 = np.random.randn(len(dataframe))>0.7
    training = ds[mask1]
    no_training = ds[~mask1]
    if validation :
        mask2 = np.random.randn(len(vali_test))>0.5
        validation = no_training[mask2]
        testing = no_training[~mask2] # ~ gives the complement of a binary chipher from 0100 to 1011 (https://data-flair.training/blogs/python-operator/)
        return training, validation, testing
    else:
        print("validation equals to testing")
        return training, no_training,no_training
    
    

In [ ]:

class Dataset ():

    def __init__(self):
        self.allDataset_features = None
        self.allDataset_targets = None
        self.training_features = None
        self.training_targets = None
        self.validation_features = None
        self.validation_targets= None
        self.testing_features = None
        self.testing_targets= None
        self.targets= None
        self.features= None
        self.targets_aux= None
        self.features_aux= None
        
    def input_data(self,path_file,sep=',',header = 0):
        
        dataset_original = pd.read_csv(path_file, sep=sep, header=header)
#         pd.options.display.float_format = '{:.4f}'.format
        
        dataset = pd.DataFrame(TMFLT_F_dataset_original.reindex(
            np.random.permutation(TMFLT_F_dataset_original.index)))
        
        #Normalization
        dataset[features] = min_max(dataset[features]) # we need to normalize just the features not the labels
        #Splitting dataset into three subsets    
        ds_training, ds_validation, ds_testing = split_dataset(dataset,validation =True)
        #All dataset features and targets
        self.allDataset_features = dataset[self.features]
        self.allDataset_targets = dataset[self.targets]
        #Training dataset
        self.training_features = ds_training[self.features]
        self.training_targets = ds_training[self.targets]
        #Validation dataset
        self.training_examples =  ds_validation[self.features]
        self.training_targets = ds_validation[self.targets]
        #Testing dataset
        self.validation_examples = ds_testing[self.features]
        self.validation_targets = ds_testing[self.targets]



In [10]:
from tensorflow.python.data import Dataset
#The tf.data API enables you to build complex input pipelines from simple, reusable pieces

# Name: 
#  pipeline_feeder
# Description:
#  The function will receive a couple of features/targets (dataframes) that will be splitted into a specific
#  number of epoch. Each epoch will containt as samples as the batchsize specified.
# Args:
#  features
#   type  -> DataFrame
#   features -> It is expected a dataframe with the columns of the features and the respective data 
#   targets  -> It is expected a dataframe with the labels. labels can be coded in one-hote or discrete 
#           -> n° labels = n° targets  they must contain the same index position (Sample 1 feature -> sample 1 target) 
#  Batch_size:
#   type  -> Integer
#   It defines the size of the batch, if batch_size is None the dataset will not be splitted (Batch gradient vs mini-batch (S.G.D))
#  Features_aux:
#   type  -> DataFrame
#   Extra features to be splitted if it is required 
#  targets_aux:
#   type  -> DataFrame
#   Extra target to be splitted if it is required # shuffle
#  Shuffle:
#   type  -> Boolean
#   The batch can be shuffled to increase randomization
#  num_epochs:
#   type  -> Integer
#   It defines the times that a batch must be loaded in memory
# Returns:
#  A  couple of target/features iterators

def pipeline_feeder(features, targets, batch_size,features_aux= None,targets_aux=None, shuffle = False, num_epochs=None):

    
    # warning: 2GB limit
    if features_aux is not None: 
        features_new = [features,features_aux] #we create a list containing extra features or extra targets
        features = pd.concat(features_new,1) #we concatenate the extra information with the original one alongisde index 1 
    elif targets_aux is not None:
        targets_new = [features,features_aux]
        target = pd.concat(targets_new,1)
   
    ds = Dataset.from_tensor_slices((features, targets))  # We call dataset function from the API data that allow us to create
                                                          # tensor objects to feed the computational graph.
    
    # Shuffle the data, if specified
    if shuffle:
        ds = ds.shuffle(10000)

    if batch_size == 0:
        ds = ds.batch(features.shape[0]).repeat(num_epochs)
    else:
        ds = ds.batch(batch_size).repeat(num_epochs)

    # Return the next batch of data
    features, labels = ds.make_one_shot_iterator().get_next()

    # labels= tf.reshape(labels,shape=(batch_size,1))
    return features, labels
    # return ds.make_one_shot_iterator()


Index(['type', 'time', 'sender', 'messageID', 'pos/0', 'pos/1', 'pos/2',
       'spd/0', 'spd/1', 'classs'],
      dtype='object')

In [27]:
features,labels = pipeline_feeder(dataset.sender,dataset.classs,10,shuffle=True,num_epochs=10)
import tensorflow as tf

sess =  tf.InteractiveSession()
for i in range(10 ) : print(sess.run(features))
sess.close()

[283 199 517   7 211 385 421 415 145  31]
[ 91 319  43 211 307 205 199 541  97 499]
[391  97 331  55 241  49  31 109 187 103]
[175  61  73 313 145 349 337 145 109 187]
[289 157 397 181  97 271 265 181 337 331]
[103  73  61  73  37 307   7  49  73 469]
[ 73 139 259 157  73 337   7 139 415  43]
[ 37  31 361 169 193 229  55 163 187 205]
[493 391 277 265 265 109  55 259 265  97]
[307 505 571 145 529 109 253  73 331 319]


C:\Users\Maturrin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
